CC = gcc
CFLAGS = -ggdb3 -O0 -std=c11 -Wall -Werror 
maxsubarray: maxsubarray.c
	$(CC) $(CFLAGS) -o maxsubarray maxsubarray.c
hello: hello.hs
	ghc -o hello hello.hs
monge: monge.hs
	ghc -o monge monge.hs
